package com.bankinc.prueba.migration;

import com.bankinc.prueba.model.Card;
import com.bankinc.prueba.model.User;
import com.bankinc.prueba.repository.CardRepository;
import com.bankinc.prueba.repository.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.*;

@Component
@ConditionalOnProperty(name = "app.migrate-users", havingValue = "true")
public class UserMigrationRunner implements ApplicationRunner {

    private final Logger log = LoggerFactory.getLogger(UserMigrationRunner.class);
    private final CardRepository cardRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public UserMigrationRunner(CardRepository cardRepository, UserRepository userRepository, PasswordEncoder passwordEncoder) {
        this.cardRepository = cardRepository;
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        log.info("UserMigrationRunner started: scanning cards to create users (if any)");

        List<Card> cards = cardRepository.findAll();
        Map<String, User> created = new HashMap<>();

        for (Card c : cards) {
            try {
                if (c.getOwner() != null) continue; // already linked
                String holder = c.getHolderName();
                if (holder == null || holder.isBlank()) continue;

                String base = normalizeUsername(holder);
                String username = base;
                int suffix = 1;
                while (userRepository.existsByUsername(username)) {
                    username = base + suffix;
                    suffix++;
                }

                // create user with random password (encoded)
                String rawPassword = UUID.randomUUID().toString();
                User u = new User();
                u.setUsername(username);
                u.setPassword(passwordEncoder.encode(rawPassword));
                u.setRoles("ROLE_USER");
                u = userRepository.save(u);

                // link card to user
                c.setOwner(u);
                cardRepository.save(c);

                created.put(username, u);
                log.info("Created user '{}' and linked card {} (holder='{}')", username, c.getCardId(), holder);
            } catch (Exception ex) {
                log.error("Failed migrating card {}: {}", c.getCardId(), ex.getMessage(), ex);
            }
        }

        if (created.isEmpty()) {
            log.info("No users were created by migration.");
        } else {
            log.info("User migration created {} users. Review credentials as passwords were autogenerated.", created.size());
        }
    }

    private String normalizeUsername(String raw) {
        String s = raw.trim().toLowerCase(Locale.ROOT);
        // replace non-alphanumeric with underscore
        s = s.replaceAll("[^a-z0-9]", "_");
        if (s.length() > 30) s = s.substring(0, 30);
        if (s.isBlank()) s = "user" + new Random().nextInt(10000);
        return s;
    }
}
